name: Build
on: [push]

jobs:
  update-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - uses: stefanzweifel/git-auto-commit-action@v4
      - run: deno task build
